change-password-feature
s0vit/shoplist-fe pull request #122
Opened 2024-08-03 20:27 UTC by shevchenkooleg

#118

2024-08-03 20:34 UTC, itbali commented
![CleanShot 2024-08-03 at 22 33 00](https://github.com/user-attachments/assets/eb5986b5-6564-4e58-8839-9bab008e7fcf)
я бы сюда перенес, сгруппировал бы с помощью ButtonGroup

2024-08-03 20:54 UTC, itbali requested changes

2024-08-03 20:54 UTC, itbali commented on src/widgets/Modal/ChangePasswordDialog.tsx
> +  const regex = /^(?=.*[0-9])(?=.*[A-Z]).*$/;
я бы унес куда-нибудь в константы в shared.
возможно стоит посмотреть другие места с паролями где это можно было бы переиспользовать

2024-08-03 20:54 UTC, itbali commented on src/widgets/Modal/ChangePasswordDialog.tsx
> +          Warning: After changing you will sign you out.
я бы предпочел сделать тут алерт чтобы привлечь внимание. Можно посмотреть разные variant, какой больше подойдет
```ts
        <Alert severity='warning' sx={{ marginTop: theme.spacing(1), paddingY: theme.spacing(0.5) }}>
```

2024-08-03 20:54 UTC, itbali commented on src/widgets/Modal/ChangePasswordDialog.tsx
> +  const handleAbortReset = () => {
```ts
  const theme = useTheme();
  ```

2024-08-03 20:54 UTC, itbali commented on src/widgets/Modal/ChangePasswordDialog.tsx
> +import { Button, Dialog, DialogActions, DialogContent, DialogTitle, TextField, Typography } from '@mui/material';
тут добавить в импорты useTheme

2024-08-03 20:54 UTC, itbali commented on src/entities/user/ui/Profile.tsx
> +  const handleConfirmResetPassword = useStableCallback(async (oldPassword: string, newPassword: string) => {
так не пойдет =) у нас используется tanstack/react-query для контроля за состоянием запроса. В лоб аксиос не используем чтобы понимать текущий статус и правильно обрабатывать error либо success. На 47 и 41 есть примеры мутации, надо сделать так же.

2024-08-06 06:11 UTC, shevchenkooleg commented
fix all ll the errors

2024-08-06 15:06 UTC, itbali approved these changes

2024-08-06 15:06 UTC, itbali commented on src/utils/hooks/useValidate.ts
> +const useValidate = () => {
чаще всего кастомные хуки используют в себе дефолтные так или иначе расширяя их возможности либо исользуя их для ререндера если что-то поменялось, либо надоборот предотвращая ненужны ререндер. 
В этом же случае больше напоминает функцию хелпер валидатор с замыканием внутри (а замыкание точно нужно?)

2024-08-06 20:36 UTC, merged