#134 source/catecory delete modal window
s0vit/shoplist-fe pull request #147
Opened 2024-10-14 19:30 UTC by shevchenkooleg

added modal window before category/payment element would delete

2024-10-14 19:34 UTC, itbali commented on src/widgets/Modal/DeleteCategoryDialog.tsx
> +            {t(' item?')}
я думаю можно без айтема. Заголовка из айтема будет достаточно. Ну и в переводах тоже можно удалить соответственно

2024-10-14 19:40 UTC, itbali requested changes

2024-10-14 19:40 UTC, itbali commented on src/pages/CategoryPage/CategoryPage.tsx
> +      setDeletingCategory({} as TCategory);
setDeletingCategory(undefined);

2024-10-14 19:40 UTC, itbali commented on src/pages/CategoryPage/CategoryPage.tsx
> +  const [deletingCategory, setDeletingCategory] = useState<TCategory>({} as TCategory);
const [deletingCategory, setDeletingCategory] = useState<TCategory>();

2024-10-14 19:40 UTC, shevchenkooleg commented on src/widgets/Modal/DeleteCategoryDialog.tsx
> +            {t(' item?')}
убрал, и ошибку литера пофиксил

2024-10-15 21:30 UTC, itbali requested changes

2024-10-15 21:30 UTC, itbali commented on src/widgets/HorizontalList/HorizontalList.tsx
> +      <DeleteCategoryDialog<TItem>
```<TItem>``` тут излишне

2024-10-15 21:30 UTC, itbali commented on src/pages/PaymentSourcesPage/PaymentSourcesPage.tsx
> +        <DeleteCategoryDialog<TPaymentSource>
```<TPaymentSource> ```тут излишне

2024-10-15 21:30 UTC, itbali commented on src/pages/CategoryPage/CategoryPage.tsx
> +        <DeleteCategoryDialog<TCategory>
```<TCategory>``` тут излишне. Тайпскрипт сам выведет типы

2024-10-20 08:15 UTC, itbali approved these changes

2024-10-20 08:16 UTC, merged