94 feauture skeletons for categories payments in calculator from main
s0vit/shoplist-fe pull request #98
Opened 2024-07-03 07:40 UTC by AleksandraBoch

#94

2024-07-03 07:51 UTC, itbali commented
что-то у меня скелетон не вырубается)

плюс он какой-то огромный. их должно быть штуки 3 и такого же размера как категории
![CleanShot 2024-07-03 at 09 50 43](https://github.com/s0vit/shoplist-fe/assets/89312941/4dd5c6e7-9bb9-45b0-9bd1-f2fcee36d6a5)

2024-07-04 07:08 UTC, itbali requested changes

2024-07-04 07:08 UTC, itbali commented on src/utils/components/Skeleton.tsx
> +    <div style={{ display: 'flex', flexDirection: 'row' }}>
```<Stack direction="row">``` вместо div'a

2024-07-04 07:08 UTC, itbali commented on src/utils/components/Skeleton.tsx
> +            height={43}
либо на пару пикселей увеличивать либо родителю падинг задавать, иначе скачет высота. Высота списка категорий 55 пикселей. Высота дива со скелетонами 53 пикселя. в момент загрузки прыгает все) а главная задача скелетона в том числе убрать эти скачки интерфейса

2024-07-04 07:38 UTC, AleksandraBoch commented on src/utils/components/Skeleton.tsx
> +    <div style={{ display: 'flex', flexDirection: 'row' }}>
done=)

2024-07-04 09:30 UTC, itbali approved these changes

2024-07-04 09:32 UTC, merged